{{ config(materialized='view') }}

SELECT  CAST(TRIM(CLAIM_ID) AS STRING) AS CLAIM_ID,
        CAST(TRIM(PATIENT_ID) AS STRING) AS PATIENT_ID,
        CAST(TRIM(ENCOUNTER_ID) AS STRING) AS ENCOUNTER_ID,
        CAST(TRIM(STATUS) AS STRING) AS STATUS,
        CAST(TRIM(CLAIM_TYPE) AS STRING) AS CLAIM_TYPE,
        CAST(TRIM(PROVIDER_NAME, '"') AS STRING) AS PROVIDER_NAME,
        CAST(TRIM(PAYER,'"') AS STRING) AS PAYER,
        TRY_CAST(TRIM(CREATED_DATE, '"') AS TIMESTAMP) AS CREATED_DATE,
        TRY_CAST(TOTAL_AMOUNT AS INTEGER) AS TOTAL_AMOUNT,
        TRY_CAST(CURRENCY AS STRING) AS CURRENCY,
        ROUND(TRY_CAST(SERVICE_CODE AS FLOAT),2) AS SERVICE_CODE,
        CASE 
            when REGEXP_LIKE(SERVICE_DESC, '^[a-zA-Z()/'' ]+$') THEN CAST(SERVICE_DESC AS STRING)
            ELSE NULL
         END AS SERVICE_DESC
FROM {{ source('RAW', 'claim') }}





