{{ config(materialized='view') }}

SELECT  CAST(TRIM(CONDITION_ID) AS STRING) AS CONDITION_ID,
        CAST(TRIM(PATIENT_ID) AS STRING) AS PATIENT_ID,
        CAST(TRIM(ENCOUNTER_ID) AS STRING) AS ENCOUNTER_ID,
        CAST(TRIM(CLINICAL_STATUS) AS STRING) AS CLINICAL_STATUS,
        TRY_CAST(CONDITION_CODE AS INTEGER) AS CONDITION_CODE,
        TRY_CAST(TRIM(CONDITION_SYSTEM) AS STRING) AS CONDITION_SYSTEM,
        TRY_CAST(TRIM(CONDITION_NAME) AS STRING) AS CONDITION_NAME,
        TRY_CAST(TRIM(ONSET_DATE) AS TIMESTAMP) AS ONSET_DATE,
        TRY_CAST(TRIM(RECORDED_DATE) AS TIMESTAMP) AS RECORDED_DATE

FROM {{ source('RAW', 'condition') }}


