{{ config(materialized='view') }}

SELECT  CAST(TRIM(ENCOUNTER_ID) AS STRING) AS ENCOUNTER_ID,
        CAST(TRIM(PATIENT_ID) AS STRING) AS PATIENT_ID,
        CAST(TRIM(STATUS) AS STRING) AS STATUS,
        CAST(CLASS_CODE AS STRING) AS CLASS_CODE,
        TRY_CAST(TRIM(ENCOUNTER_TYPE) AS STRING) AS ENCOUNTER_TYPE,
        TRY_CAST(TRIM(START_DATE) AS TIMESTAMP) AS START_DATE,
        TRY_CAST(TRIM(END_DATE) AS TIMESTAMP) AS END_DATE,
        CAST(TRIM(PROVIDER_NAME, '"') AS STRING) AS PROVIDER_NAME,
        CASE 
            WHEN REGEXP_LIKE(PRACTITIONER, '^(DR\.|Dr\.)?[a-zA-Z0-9()/'' ]+$') THEN CAST(PRACTITIONER AS STRING)
            ELSE NULL
        END AS PRACTITIONER

FROM {{ source('RAW', 'encounter') }}

