{{ config(materialized='view') }}

SELECT  CAST(TRIM(MEDICATION_ID) AS STRING) AS MEDICATION_ID,
        CAST(TRIM(PATIENT_ID) AS STRING) AS PATIENT_ID,
        CAST(TRIM(ENCOUNTER_ID) AS STRING) AS ENCOUNTER_ID,
        CAST(TRIM(STATUS) AS STRING) AS STATUS,
        CAST(MEDICATION_CODE AS INTEGER) AS MEDICATION_CODE,
        TRY_CAST(TRIM(MEDICATION_NAME, '"') AS STRING) AS MEDICATION_NAME,
        TRY_CAST(TRIM(AUTHORED_DATE) AS TIMESTAMP) AS AUTHORED_DATE,
        CASE 
            WHEN REGEXP_LIKE(REQUESTER, '^(DR\.|Dr\.)?[a-zA-Z0-9()/'' ]+$') THEN CAST(REQUESTER AS STRING)
            ELSE NULL
        END AS REQUESTER
FROM {{ source('RAW', 'medication_request') }}

