{{ config(materialized='view') }}

SELECT  CAST(TRIM(PATIENT_ID) AS STRING) AS PATIENT_ID,
        CAST(TRIM(REGEXP_REPLACE(FIRST_NAME, '[0-9]+$', '')) AS STRING) AS FIRST_NAME,
        CAST(TRIM(REGEXP_REPLACE(LAST_NAME, '[0-9]+$', '')) AS STRING) AS LAST_NAME,
        CAST(TRIM(GENDER) AS STRING) AS GENDER,
        TRY_CAST(TRIM(BIRTH_DATE) AS TIMESTAMP) AS BIRTH_DATE,
        {{ age_calculate('BIRTH_DATE') }} AS AGE,
        TRY_CAST(TRIM(RACE) AS STRING) AS RACE,
        TRY_CAST(TRIM(ETHNICITY) AS STRING) AS ETHNICITY,
        CAST(TRIM(BIRTH_PLACE, '"') AS STRING) AS BIRTH_PLACE,
        CAST(TRIM(STATE) AS STRING) AS CITY,
        CAST(TRIM(POSTAL_CODE) AS STRING) AS POSTAL_CODE,
        CAST(MARITAL_STATUS AS STRING) AS COUNTRY,
        CAST(TRIM(LANGUAGE) AS STRING) AS MARITAL_STATUS

FROM {{ source('RAW', 'patient') }}
