{{ config(materialized='view') }}

SELECT  CAST(TRIM(PROCEDURE_ID) AS STRING) AS PROCEDURE_ID,
        CAST(TRIM(PATIENT_ID) AS STRING) AS PATIENT_ID,
        CAST(TRIM(ENCOUNTER_ID) AS STRING) AS ENCOUNTER_ID,
        CAST(TRIM(STATUS) AS STRING) AS STATUS,
        TRY_CAST(TRIM(PROCEDURE_CODE) AS INTEGER) AS PROCEDURE_CODE,
        CAST(TRIM(PROCEDURE_SYSTEM, '"') AS STRING) AS PROCEDURE_SYSTEM,
        TRY_CAST(TRIM(PROCEDURE_NAME,'"') AS STRING) AS PROCEDURE_NAME,
        TRY_CAST(PERFORMED_START AS TIMESTAMP) AS PERFORMED_START,
        TRY_CAST(PERFORMED_END AS TIMESTAMP) AS PERFORMED_END
FROM {{ source('RAW', 'procedure') }}




